name: opticonnect_sdk
description: >
   OptiConnect SDK integrates with Opticon's BLE OPN-2500 and OPN-6000 scanners, 
   enabling Bluetooth connection management, data streaming, and command control.
version: 1.0.15
homepage: https://github.com/OpticonOSEDevelopment/opticonnect_sdk_flutter
repository: https://github.com/OpticonOSEDevelopment/opticonnect_sdk_flutter
documentation: https://opticonosedevelopment.github.io/opticonnect_sdk_flutter
issue_tracker: https://github.com/OpticonOSEDevelopment/opticonnect_sdk_flutter/issues

environment:
   sdk: ^3.5.0
   flutter: ">=2.12.0"

dependencies:
   device_info_plus: ^10.1.2
   flutter:
      sdk: flutter
   get_it: ^8.0.2
   injectable: ^2.5.0
   permission_handler: ^11.3.1
   mutex: ^3.1.0
   logger: ^2.4.0
   sqflite: ^2.3.3+1
   path_provider: ^2.1.5
   path: ^1.9.0
   sqflite_common_ffi: ^2.3.4
   flutter_blue_plus: ^1.33.6
   flutter_blue_plus_windows: ^1.24.19
   path_provider_windows: ^2.3.0

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^4.0.0
   injectable_generator: ^2.6.2
   build_runner: ^2.4.12

flutter:
   assets:
      - assets/
      - assets/database/

platforms:
   android:
   ios:
   windows:
   macos:
