name: opticonnect_sdk
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
   sdk: ^3.5.0
   flutter: ">=1.17.0"

dependencies:
   device_info_plus: ^10.1.2
   flutter:
      sdk: flutter
   flutter_blue_plus: ^1.32.12
   get_it: ^7.7.0
   injectable: ^2.4.4
   mockito: ^5.4.4
   permission_handler: ^11.3.1
   mutex: ^3.1.0

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^4.0.0
   injectable_generator: ^2.6.2
   build_runner: ^2.4.12
